filter:
  excluded_paths:
    - "src/*Bundle/DataFixtures/ORM/"
    - "app/"
    - "web/"

before_commands:
    - "composer install"

checks:
    php: true

build:
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=.coverage'
                coverage:
                    file: '.coverage'
                    format: 'clover'
    environment:
        timezone: 'Europe/Amsterdam'
        php:
            version: '7.1'
            ini:
                'date.timezone': 'Europe/Amsterdam'
    dependencies:
        # Runs before inferred commands
        before: []
        # Overwrites inferred commands
        override: []
        # Runs after inferred commands
        after: []
    # Run after dependencies
    project_setup:
        before: []
        override: []
        after: []
    nodes:
        tests: true
        analysis:
            tests:
                override:
                    - phpcs-run
                    - php-scrutinizer-run

build_failure_conditions:
  # No critical issue is introduced (existing ones are tolerated)
  - 'issues.label("coding-style").exists'
  # No new critical issue is introduced (existing ones are tolerated)
  - 'issues.label("coding-style").new.exists'
  # No critical issue is present
  - 'issues.severity(= MINOR).exists'
  # No new critical issue is introduced (existing ones are tolerated)
  - 'issues.severity(= MINOR).new.exists'
  # Class has no tests
  - 'classes.metric("php_code_coverage.coverage", = 0).exists'
  # Rating is C or worse for existing classes
  - 'elements.rating(<= C).exists'
  # Rating is C or worse is introduced
  - 'elements.rating(<= C).new.exists'
  # Code Quality Rating drops below 8
  - 'project.metric("scrutinizer.quality", < 8)'
  # Code Coverage decreased from previous inspection
  - 'project.metric_change("scrutinizer.test_coverage", < 0)'